services:
  dozzle:
    image: amir20/dozzle:latest
    pull_policy: always
    container_name: dozzle
    restart: unless-stopped
    environment:
      - DOZZLE_REMOTE_AGENT=${DOZZLE_REMOTE_AGENT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '65000:8080'
