version: "3"
networks:
  unklab:
    external: true

services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 64000:8080
    networks:
      - unklab
