version: "3"
networks:
  unklab:
    external: true

services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    environment:
      - DOZZLE_REMOTE_AGENT=10.104.0.3:7007
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - unklab
